# Generated by Django 3.2.23 on 2024-01-28 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emotionalBot', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrainData',
        ),
    ]
