# Generated by Django 3.2.23 on 2024-01-28 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emotionalBot', '0003_traindata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrainData',
            new_name='Statement',
        ),
    ]
