# Generated by Django 3.2.23 on 2024-01-29 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emotionalBot', '0004_rename_traindata_statement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Statement',
        ),
    ]
