# Generated by Django 3.2.23 on 2024-01-29 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emotionalBot', '0005_delete_statement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('response', models.TextField()),
            ],
        ),
    ]
